Drink.create!(name:'',price:110,genre:'')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'Voluic',    price:100,genre:'',image:'/drink/')
Drink.create!(name:'Voluic',    price:100,genre:'',image:'/drink/')
Drink.create!(name:'Voluic',    price:100,genre:'',image:'/drink/')
Drink.create!(name:'Voluic',    price:100,genre:'',image:'/drink/')
Drink.create!(name:'Voluic',    price:100,genre:'',image:'/drink/')
Drink.create!(name:'Voluic',    price:100,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')
Drink.create!(name:'ホットレモン',price:110,genre:'',image:'/drink/')