Drink.create!(name:'純粋りんご',             price:110,genre:'1',image:'/drink/りんご.jpg')
Drink.create!(name:'力水',                  price:110,genre:'2',image:'/drink/力水.jpg')
Drink.create!(name:'メッツ',                 price:110,genre:'3',image:'/drink/メッツ.jpg')
Drink.create!(name:'ふるふるゼリー',          price:110,genre:'4',image:'/drink/ふるふるゼリー.png')
Drink.create!(name:'red bull',              price:190,genre:'5',image:'/drink/red bull.png')
Drink.create!(name:'red bull',              price:190,genre:'5',image:'/drink/red bull.png')
Drink.create!(name:'ファイア 挽きたて微糖',    price:100,genre:'6',image:'/drink/fire_コーヒー.jpg')
Drink.create!(name:'ファイア ワンデイ ブラック',price:130,genre:'7',image:'/drink/black_コーヒー.jpg')
Drink.create!(name:'ファイア ワンデイ ブラック',price:130,genre:'7',image:'/drink/black_コーヒー.jpg')
Drink.create!(name:'ファイア ワンデイ ブラック',price:130,genre:'7',image:'/drink/black_コーヒー.jpg')
Drink.create!(name:'アミノサプリＣ',          price:110,genre:'8',image:'/drink/amino .jpg')
Drink.create!(name:'アミノサプリＣ',          price:110,genre:'8',image:'/drink/amino .jpg')

Drink.create!(name:'生茶',                  price:120,genre:'9',image:'/drink/生茶.png')
Drink.create!(name:'生茶',                  price:120,genre:'9',image:'/drink/生茶.png')
Drink.create!(name:'麦茶',                  price:110,genre:'10',image:'/drink/麦茶.png')
Drink.create!(name:'麦茶',                  price:110,genre:'10',image:'/drink/麦茶.png')
Drink.create!(name:'おいしい無糖',           price:130,genre:'11',image:'/drink/午後tea.png')
Drink.create!(name:'おいしい無糖',           price:130,genre:'11',image:'/drink/午後tea.png')
Drink.create!(name:'レモンスカッシュ',        price:110,genre:'12',image:'/drink/レモンスカッシュ.jpg')
Drink.create!(name:'Volvic',               price:100,genre:'13',image:'/drink/ヴォルヴィック.jpg')
Drink.create!(name:'Volvic',               price:100,genre:'13',image:'/drink/ヴォルヴィック.jpg')
Drink.create!(name:'Volvic',               price:100,genre:'13',image:'/drink/ヴォルヴィック.jpg')
Drink.create!(name:'Volvic',               price:100,genre:'13',image:'/drink/ヴォルヴィック.jpg')
Drink.create!(name:'Volvic',               price:100,genre:'13',image:'/drink/ヴォルヴィック.jpg')

Drink.create!(name:'生茶',                  price:110,genre:'14',image:'/drink/hot_生茶.png')
Drink.create!(name:'ほうじちゃ',             price:110,genre:'15',image:'/drink/hot_ほうじちゃ.jpg')
Drink.create!(name:'ミルクティー',           price:110,genre:'16',image:'/drink/hot_午後.jpg')
Drink.create!(name:'アップルティー',         price:110,genre:'17',image:'/drink/hot_アップルティー.jpg')
Drink.create!(name:'ホットレモン',           price:110,genre:'18',image:'/drink/hot_ホットレモン.jpg')
Drink.create!(name:'直火ブレンド',           price:100,genre:'19',image:'/drink/hot_fire コーヒー.jpg')
Drink.create!(name:'カフェオレ',             price:110,genre:'20',image:'/drink/hot_贅沢カフェオレ.jpg')
Drink.create!(name:'リフレッシュブラック',    price:100,genre:'21',image:'/drink/hot_black_コーヒー.jpg')
Drink.create!(name:'ミルクココア',           price:110,genre:'22',image:'/drink/hot_ココア.jpg')
Drink.create!(name:'牛乳使用ラテ',           price:120,genre:'23',image:'/drink/hot_ラテ.jpg')
Drink.create!(name:'バリスタコーヒー',        price:120,genre:'24',image:'/drink/hot_バリスタ.png')
Drink.create!(name:'目覚めの深煎り',         price:120,genre:'25',image:'/drink/hot_black_last_コーヒー.jpg')